[package]
name = "easy_mmap"
version = "0.1.0"
edition = "2021"
author = "Tiago Antunes <tiago.melo.antunes@gmail.com>"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mmap = "0.1.1"